name: Build Expo Web

on:
  push:
    branches: [main, feat/add-basic-db-schema]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend deps
        working-directory: TreeGuardiansExpo
        run: npm install

      - name: Build Expo web
        working-directory: TreeGuardiansExpo
        run: npx expo export --platform web

      - name: Upload build artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: expo-dist
          path: TreeGuardiansExpo/dist

      - name: Commit build output
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add TreeGuardiansExpo/dist
          git commit -m "CI: build expo web" || echo "No changes"
          git push